### ISSUE TITLE
Infografia Andre Emmanuel Luna Gonzalez

### ISSUE THREAD

**Issue by AndreLuna6** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-AndreLuna6#1]
[Infografia_AndreEmmanuelLunaGonzalez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-AndreLuna6/files/14133322/Infografia_AndreEmmanuelLunaGonzalez.pdf)

**Comment by FedericoVictorianoSierra** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
